#!/system/.xzdr/bin/sh
#
# Multi Recovery for many Sony Xperia devices!
#
# Authors:
#   [NUT], AngelBob, Olivier and shoey63
#
# - Thanks go to DooMLoRD for the keycodes and a working example!
# - My gratitude also goes out to Androxyde for his sometimes briliant
#   ideas to simplify things while writing the scripts!
#
###########################################################################

set +x
PATH="/system/.xzdr/bin:/system/.xzdr/sbin:/sbin"

_TIME=`busybox date +"%H:%M:%S"`
echo "${_TIME} >> $*" >> $XZDRLOGFILE
$* 2>&1 >> $XZDRLOGFILE
_RET=$?
echo "${_TIME} >> RET=${_RET}" >> $XZDRLOGFILE

exit ${_RET}
